// import '../style/globals.css'
// import { Inter } from 'next/font/google'
// import Head from 'next/head'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'My-Blog-App',
//   description: 'Blog generated by next-js',
  
// }


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//         <Head>
//         <link href="https://fonts.googleapis.com/css2?family=Caprasimo&display=swap" rel="stylesheet"/>
//         </Head>
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
import '../style/globals.css'

export default function App({ Component, pageProps }) {
  return (
    <Component {...pageProps} /> 
  )
}


